apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-nginx5
  name: hello-nginx5
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-nginx5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-nginx5
    spec:
      containers:
      - image: ghcr.io/nlloyd1971/demo:latest
        imagePullPolicy: Always
        name: demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-nginx5
  name: hello-nginx-lb5
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-nginx5
  sessionAffinity: None
  type: LoadBalancer
